-- API route(apps/dashboard/src/app/api/jobs/route.ts)가 INSERT하는 컬럼 중
-- 현재 jobs 테이블에 없는 것들 추가
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'youtube_watch';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS target_type TEXT DEFAULT 'all_devices';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS target_value INTEGER DEFAULT 100;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS assigned_count INTEGER DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS completed_count INTEGER DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS failed_count INTEGER DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS priority BOOLEAN DEFAULT false;
